comin_plugin:
  name: wind_3d
  version: 1
  physics: AES
  parameters:
    avg_interval: 300  # Averaging window [seconds]
    cut_in: 0.0        # Wind speed below this threshold is set to NaN [m/s]
